title: Kieranties Codes
email: Kieran@Kieranties.com
description: Musings, thoughts, ramblings, code.
twitter_username: Kieranties
github_username:  Kieranties
lang: en-GB
theme: jekyll-theme-cayman
repository: Kieranties/Kieranties.github.io
show_downloads: false
markdown: kramdown
paginate: 5
permalink: /:year/:month/:day/:title

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions

exclude:
  - CNAME
  - .vscode/