# Theme
# Using github pages remote themes
remote_theme          : mmistakes/minimal-mistakes
minimal_mistakes_skin : "dark"

# Site Settings
locale              : "en-GB"
title               : Kieranties Codes
title_seperator     : "|" # used for seo friendly page titles
name                : "Kieran Marron" # site wide author
description         : Musings, thoughts, ramblings, code.
url                 : https://blog.kieranties.com
baseurl             : ''
repository          : Kieranties/Kieranties.github.io
breadcrumbs         : false
search              : true
search_full_content : true

comments:
  provider: "disqus"
  disqus:
    shortname: kierantiescodes

twitter:
  username: "Kieranties"
og_image: "/assets/images/avatar-head.png"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-105831988-1"

author:
  name   : "Kieran Marron"
  avatar : "/assets/images/avatar-head.png"
  bio    : "Coding my way in and out of problems."
  location: Bristol, UK
  email  : Kieran@Kieranties.com
  uri    : "http://Kieranties.com"
  twitter: Kieranties
  github : Kieranties
  linkedin: Kieranties
  stackoverflow: 1749821/kieranties


paginate  : 5
permalink : /:year/:month/:day/:title
timezone  : Europe/London

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  - CNAME
  - .vscode/
  - build/
keep_files:
  - .git
  - .svn

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # all
  - scope:
      path: ""
    values:
      author_profile: true
      classes: wide

  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      author_profile: true
      comments: true
      share: true
      related: true
